### ISSUE TITLE
Fails to pull MSSQL docker image - outdated?

### ISSUE THREAD

**Issue by HariSekhon** [OctopusSamples/OctopusHelmChart#11]
Looks like the docker image for MSSQL in the chart is outdated?

```
octopusdeploy-mssql-linux-5f99c8c6d9-x666z   0/1     ImagePullBackOff   0          114s
```
describe:
```
  Normal   Pulling           11s   kubelet            Pulling image "microsoft/mssql-server-linux:2017-CU5"
  Warning  Failed            10s   kubelet            Failed to pull image "microsoft/mssql-server-linux:2017-CU5": rpc error: code = Unknown desc = Error response from daemon: pull access denied for microsoft/mssql-server-linux, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Warning  Failed            10s   kubelet            Error: ErrImagePull
  Normal   BackOff           9s    kubelet            Back-off pulling image "microsoft/mssql-server-linux:2017-CU5"
  Warning  Failed            9s    kubelet            Error: ImagePullBackOff
```
```
$ docker login
Authenticating with existing credentials...
Login Succeeded
```
```
$ docker pull microsoft/mssql-server-linux:2017-CU5
Error response from daemon: pull access denied for microsoft/mssql-server-linux, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by HariSekhon** [comment]
Microsoft doesn't seem to have the 2017 community edition available any more:

https://hub.docker.com/_/microsoft-mssql-server

Looks like the Octopus chart is using this outdated chart which is the problem, as per the readme here:

https://github.com/helm/charts/tree/master/stable/mssql-linux

**Comment by dacwebb** [comment]
Thanks for your comment @HariSekhon , helped me find a simple fix for it.
I forked a copy for my own experimenting and fixed it [here](https://gitlab.com/dacweb/OctopusHelmChart) where it uses MSSQL 2019-CU18-ubuntu-20.04 and the containers seem to run successfully.
I believe the docker image is correct specified in this repo, but the reference to where it is located has changed.

On line 14 in [OctopusHelmChart/blob/master/charts/mssql-linux/values.yaml](https://github.com/OctopusSamples/OctopusHelmChart/blob/master/charts/mssql-linux/values.yaml)
Instead of:

```yaml
image:
  repository: microsoft/mssql-server-linux
  tag: 2017-CU5
```

It can probably just be changed to:
```yaml
image:
  repository: mcr.microsoft.com/mssql/server
  tag: 2017-CU5-ubuntu
```

I hadn't tested this with the same repository link, but the new one worked fine for other tags from [Microsoft's docker hub](https://hub.docker.com/_/microsoft-mssql-server?tab=description). It's possible the only reason this broke for mssql server is that the old tag "2017-CU5" isn't in the docker hub any more, and instead has ubuntu at the end of the tag.

**Comment by harrisonmeister** [comment]
Closing this issue as we have a replacement Helm chart [here](https://github.com/OctopusDeploy/helm-charts)
